---
- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - raw: sudo apt-get update
    - raw: sudo apt-get -y install python3-simplejson

- hosts: all
  become: yes
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - nginx
    - mysql
    - redis
    - php
    - xdebug
    - composer
    - app
