---
- name: Install xDebug
  become: yes
  apt: pkg=php{{ php.version }}-xdebug state=latest

- name: Change default xdebug config
  become: yes
  template: src=default.tpl dest=/etc/php/{{ php.version }}/mods-available/xdebug.ini
  notify: restart php{{ php.version }}-fpm
